name: trainer
inputs:
- {name: transformed_train_data_path, type: {GCPPath: {data_type: CSV}}}
- {name: suffix, type: String}
outputs:
- {name: trained_model_path, type: {GCPPath: {data_type: PKL}}}
implementation:
  container:
    image: ${tagged_name}
    command:
      - poetry
      - run
      - python
      - /component/src/trainer.py
    args:
      - {inputPath: transformed_train_data_path}
      - {inputValue: suffix}
      - {outputPath: trained_model_path}
