name: trainer
inputs:
- {name: transformed_train_data_path, type: dataset}
- {name: suffix, type: String}
outputs:
- {name: trained_model_path, type: model}
implementation:
  container:
    image: ${tagged_name}
    args:
      - {inputUri: transformed_train_data_path}
      - {inputValue: suffix}
      - {outputUri: trained_model_path}
